/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/Favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieDetailImdbIDRouteImport } from './routes/MovieDetail.$imdbID'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/Favorites',
  path: '/Favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieDetailImdbIDRoute = MovieDetailImdbIDRouteImport.update({
  id: '/MovieDetail/$imdbID',
  path: '/MovieDetail/$imdbID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Favorites': typeof FavoritesRoute
  '/MovieDetail/$imdbID': typeof MovieDetailImdbIDRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Favorites': typeof FavoritesRoute
  '/MovieDetail/$imdbID': typeof MovieDetailImdbIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Favorites': typeof FavoritesRoute
  '/MovieDetail/$imdbID': typeof MovieDetailImdbIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Favorites' | '/MovieDetail/$imdbID'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Favorites' | '/MovieDetail/$imdbID'
  id: '__root__' | '/' | '/Favorites' | '/MovieDetail/$imdbID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  MovieDetailImdbIDRoute: typeof MovieDetailImdbIDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Favorites': {
      id: '/Favorites'
      path: '/Favorites'
      fullPath: '/Favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MovieDetail/$imdbID': {
      id: '/MovieDetail/$imdbID'
      path: '/MovieDetail/$imdbID'
      fullPath: '/MovieDetail/$imdbID'
      preLoaderRoute: typeof MovieDetailImdbIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  MovieDetailImdbIDRoute: MovieDetailImdbIDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
